# Generated by Django 5.0.6 on 2024-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksymbol',
            name='last_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocksymbol',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
